application: bloggzen
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /components
  static_dir: components

- url: /.*
  script: blag.app

libraries:
- name: jinja2
  version: latest
